# commit to be tagged for the new release
commit = "HEAD"

project_name = "terraform-provider-talos"
github_repo = "siderolabs/terraform-provider-talos"
match_deps = "^github.com/(siderolabs/[a-zA-Z0-9-]+)$"

previous = "v0.4.0"
pre_release = false

[notes]

    [notes.updates]
        title = "Component Updates"
        description = """\
Talos sdk: v1.7.0
"""
