name: acceptance-tests
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
on:
  pull_request:
    paths:
      - 'go.mod'
      - 'go.sum'
      - '**.go'
jobs:
  acc-tests:
    runs-on:
      - self-hosted
      - generic
    env:
      GOTOOLCHAIN: local
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Set up libvirt
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bridge-utils \
            dnsmasq-base \
            virtinst \
            libvirt-daemon \
            libvirt-daemon-system \
            qemu-kvm \
          ;

          echo -e "<pool type='dir'>\n<name>default</name>\n<target>\n<path>/pool-default</path>\n</target>\n</pool>" > pool.xml
          sudo mkdir /pool-default
          sudo chmod a+rwx /pool-default
          sudo virsh pool-define pool.xml
          sudo virsh pool-start default
          echo 'security_driver = "none"' | sudo tee --append /etc/libvirt/qemu.conf
          sudo systemctl restart libvirtd
      - name: acceptance-test
        env:
          TERRAFORM_LIBVIRT_TEST_DOMAIN_TYPE: qemu
          LIBVIRT_DEFAULT_URI: qemu:///system
          CI: "true"
        run: |
          sudo -E make testacc
