name: check-dirty
on:
  pull_request:
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: dirty-check
        run: |
          make check-dirty
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
